
// Generated by CoffeeScript 1.11.1
var AdminTreeItem,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AdminTreeItem = (function(superClass) {
  extend(AdminTreeItem, superClass);

  function AdminTreeItem() {
    AdminTreeItem.__super__.constructor.call(this);
    this.add_attr({
      id: -1,
      directory_id: -1,
      text: "",
      type: "file",
      children: new Lst,
      state: {
        opened: false,
        disabled: false
      },
      link_model: new Model
    });
  }

  return AdminTreeItem;

})(Model);
// Generated by CoffeeScript 1.11.1
var model_status,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

model_status = (function(superClass) {
  extend(model_status, superClass);

  function model_status() {
    model_status.__super__.constructor.call(this);
    this.add_attr({
      count_users: 0,
      count_models: 0,
      ram_usage_virt: 0,
      ram_usage_res: 0,
      count_sessions: 0,
      users: [],
      data_list: []
    });
  }

  return model_status;

})(Model);
